#!/usr/bin/env perl

use strict;
use warnings;

my constant $temp_filename = "/tmp/jot-" . time();
my constant $home_dir = $ENV{"HOME"};
my $editor = $ENV{EDITOR} || "vim";
system $editor => $temp_filename;

my $contents = `cat $temp_filename`;

my $contents_with_separator = $contents . "\f\n";

my constant $jot_dir = "$home_dir/jot";
my constant $jot_file = "$jot_dir/jot";

`mkdir -p $jot_dir`;
`touch $jot_file`;

open(my $fh, '>> :encoding(UTF-8)', "$jot_file")
    or die "Error: couldn’t open file.";
say $fh $contents_with_separator;
close $fh;

# TODO for future use:
#     git diff --unified=0 | tail -n +6 | perl -pe 's/^\+//'
#
# Alternatively (probably better):
#
#     git difftool -y \
#         --extcmd="diff --changed-group-format='%>' --unchanged-group-format=''"
