#!/usr/bin/env perl

use strict;
use warnings;

my ($pop) = @ARGV;

# No argument means that a note is to be added.
if (not defined $pop) {
    add_jot();
} elsif ($pop ne "pop") {
    die "jot: error: unknown argument “$pop”";
}

sub add_jot {
    my constant $temp_filename = "/tmp/jot-" . time();
    my constant $home_dir = $ENV{"HOME"};
    my $editor = $ENV{EDITOR} || "vim";
    system $editor => $temp_filename;

    my $contents = `cat $temp_filename`;

    my $contents_with_separator = $contents . "\f\n";

    my constant $jot_dir = "$home_dir/jot";
    `mkdir -p $jot_dir`;
    chdir "$jot_dir";
    `touch $jot_dir/jot`;

    open(my $fh, '>> :encoding(UTF-8)', "./jot")
        or die "jot: error: couldn’t open file.";
    say $fh $contents_with_separator;
    close $fh;
};
